New year enhancements

diff --git a/zshrc-config/aliases/integrations/docker b/zshrc-config/aliases/integrations/docker
--- a/zshrc-config/aliases/integrations/docker
+++ b/zshrc-config/aliases/integrations/docker
@@ -1,19 +1,15 @@
 #!/bin/bash
+
 export DOCKER_SCRIPTS_PATH="integrations/docker_scripts"
 
 alias dk="$HOME/<PATH>/run.sh $@"
 alias dkclean="sh $ZSH_CUSTOM_CONFIG_ALIASES/$DOCKER_SCRIPTS_PATH/docker_clean_all.sh"
 alias dkpurge="sh $ZSH_CUSTOM_CONFIG_ALIASES/$DOCKER_SCRIPTS_PATH/docker_purge.sh"
-alias dkcreate="sh $ZSH_CUSTOM_CONFIG_ALIASES/$DOCKER_SCRIPTS_PATH/docker_turn_on.sh"
-alias dklightclean="sh $ZSH_CUSTOM_CONFIG_ALIASES/$DOCKER_SCRIPTS_PATH/docker_light_clean.sh"
+alias dklightclean="docker rmi $(docker images -f "dangling=true" -q) -f"
 alias dkprune='docker system prune --volumes'
 alias dkstatus="docker ps -q | xargs  docker stats --no-stream"
 alias unsetkube='kubectl config unset current-context'
 alias dkstop='docker stop $(docker ps -aq)'
-# dkrm='docker stop $(docker ps -a -q) && docker rm $(docker ps -a -q)' && docker volume prune
-
-# how-to-remove-docker-images-containers-and-volumes
-# https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes
 
 function dklist() {
     echo '\n*** images ***' && docker images -a
@@ -25,6 +21,54 @@ alias dkps='docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Ports}}\t{{.Names}
 
 # You can put this into ~/.docker/config.json to make it the default format.
 alias dki='echo "\n___DOCKER IMAGES____ " && docker images -a && echo "\n___DOCKER COMPOSE IMAGES____ " && docker-compose images'
+
+usage="dkmanage [-c] [-i] [-v] [-a] -- function to manage Docker resources within the system
+
+Options:
+    -c, --containers     Stops and removes all the containers
+    -i, --images         Removes all the images
+    -v, --volumes        Removes all the volumes
+    -a, --all            Stops and removes containers, images and volumes
+    -s, --soft           Removes all dangling images, stopped containers, networks not being used,
+                         all images without at least one container associated to them and all build cache"
+
+function dkmanage() {
+    if [[ $# -eq 0 ]]; then
+       echo "$usage"; break;
+    fi
+
+    while [ $# -gt 0 ]
+    do
+        case "$1" in
+        (-c|--containers)
+            echo "Stopping containers..."
+            sudo docker container stop $(docker container ls -aq)
+            echo "Removing containers..."
+            sudo docker rm $(sudo docker ps -aq) --force --volumes ;;
+
+        (-i|--images)
+            echo "Removing images..."
+            sudo docker rmi $(sudo docker images -q) --force ;;
+
+        (-v|--volumes)
+            echo "Removing volumes..."
+            docker volume rm $(docker volume ls) ;;
+
+        (-s|--soft)
+            docker rm $(docker ps -q -f status=exited)
+            docker rmi $(docker images -f "dangling=true" -q) -f
+            docker system prune -a ;;
+
+        (-a|--all)
+            echo "Deep cleaning docker: containers, images and volumes..."
+            dkmanage -c -i -v ;;
+
+        (-*) echo "$0: error: unrecognized option $1"; echo "$0: $usage"; exit 1 ;;
+        (*)  echo "$0: $usage"; break ;;
+        esac
+        shift
+    done
+}
 
 ####
 # DOCKER PERMISSION ISSUES?
@@ -39,3 +83,6 @@ alias dki='echo "\n___DOCKER IMAGES____ " && docker images -a && echo "\n___DOCK
 # 	$ python -m smtpd -n -c DebuggingServer localhost:1025
 # 		TIP: Enter to the container through bash
 # 		(docker exec -it -u root <container_name> bash) and run the python command
+
+# how-to-remove-docker-images-containers-and-volumes
+# https://www.digitalocean.com/community/tutorials/how-to-remove-docker-images-containers-and-volumes
