integrations: from script to case function

diff --git a/zshrc-config/aliases/integrations/docker b/zshrc-config/aliases/integrations/docker
--- a/zshrc-config/aliases/integrations/docker
+++ b/zshrc-config/aliases/integrations/docker
@@ -22,7 +22,7 @@ alias dkps='docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Ports}}\t{{.Names}
 # You can put this into ~/.docker/config.json to make it the default format.
 alias dki='echo "\n___DOCKER IMAGES____ " && docker images -a && echo "\n___DOCKER COMPOSE IMAGES____ " && docker-compose images'
 
-usage="dkmanage [-c] [-i] [-v] [-a] -- function to manage Docker resources within the system
+dkmanage_usage="dkmanage [-c] [-i] [-v] [-a] -- function to manage Docker resources within the system
 
 Options:
     -c, --containers     Stops and removes all the containers
@@ -34,7 +34,7 @@ Options:
 
 function dkmanage() {
     if [[ $# -eq 0 ]]; then
-       echo "$usage"; break;
+       echo "$dkmanage_usage"; break;
     fi
 
     while [ $# -gt 0 ]
@@ -63,8 +63,8 @@ function dkmanage() {
             echo "Deep cleaning docker: containers, images and volumes..."
             dkmanage -c -i -v ;;
 
-        (-*) echo "$0: error: unrecognized option $1"; echo "$0: $usage"; exit 1 ;;
-        (*)  echo "$0: $usage"; break ;;
+        (-*) echo "$0: error: unrecognized option $1"; echo "$0: $dkmanage_usage"; exit 1 ;;
+        (*)  echo "$0: $dkmanage_usage"; break ;;
         esac
         shift
     done
diff --git a/zshrc-config/aliases/nruault/custom b/zshrc-config/aliases/nruault/custom
--- a/zshrc-config/aliases/nruault/custom
+++ b/zshrc-config/aliases/nruault/custom
@@ -3,16 +3,17 @@
 alias awesome='cat $ZSH_CUSTOM_CONFIG_FILES/nruault/assets/awesome.txt'
 alias crypto\?='go run $ZSH_CUSTOM_CONFIG_FILES/aliases/nruault/assets/crypto.go &'
 
+alias noel.io\?='check_noelio_domain'
 function check_noelio_domain() {
     # Checks for internet connectivity.
     if ping -q -c 1 -W 1 8.8.8.8 >/dev/null; then; else exit 1; fi
 
     domain_expiry_date=$(whois noel.io | grep "Registry Expiry Date" | grep -oE '(\d{4})-(\d\d)-(\d\d)' | sed 's/[\._-]//g')
 
-    current_epoch_time=`date -jf %Y%m%d $(date +%Y%m%d) +%s`
-    domain_expity_date_epoch=`date -jf %Y%m%d $domain_expiry_date +%s`
+    current_epoch_time=$(date -jf %Y%m%d $(date +%Y%m%d) +%s)
+    domain_expity_date_epoch=$(date -jf %Y%m%d $domain_expiry_date +%s)
 
-    days_until_expiration=$(( (domain_expity_date_epoch - current_epoch_time) / 86400 ))
+    days_until_expiration=$(((domain_expity_date_epoch - current_epoch_time) / 86400))
 
     if [[ "$1" == "bash:request" ]]; then
         if ((days_until_expiration < 30)); then
@@ -23,13 +24,12 @@ function check_noelio_domain() {
     fi
     # exit 0
 }
-
 (check_noelio_domain "bash:request" &) # https://stackoverflow.com/a/7687722/4349318
 
-alias noel.io\?='check_noelio_domain'
+function env_var_is_empty() {
+    [ -z "$1" ]
+}
 
-
-# CD ANYWHERE aliases
 alias goto=go_to_dir_on_specific_folder # A $COMPANY_DIRECTORY needs to be configured
 
 # go_to_dir_on_specific_folder will try to find a directory that matches
@@ -105,6 +105,70 @@ function go_to_dir_on_specific_folder() {
     fi
 }
 
-function env_var_is_empty() {
-    [ -z "$1" ]
+source_integrations_usage="source_integrations [integrations...] -- Sources any integration given a list
+
+3rd party integrations must be added to this script manually. So far we can handle the next
+Options:
+    gcloud     Loads Google Cloud integration
+    nvm        Loads NVM integration
+    aws        Prints how to load Amazon Web Service integration
+    flutter    Loads Flutter integration
+"
+
+function source_integrations() {
+    source_integrations_start=$(python3 -c 'from time import time; print(int(round(time() * 1000)))')
+
+    if [[ $# -eq 0 ]]; then
+        echo "$source_integrations_usage"
+        exit 0
+    fi
+
+    while [ $# -gt 0 ]; do
+        case "$1" in
+        gcloud)
+            echo "Loading GCloud integration"
+            GCLOUD_SDK_PATH="/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk"
+
+            # The next line updates PATH for the Google Cloud SDK.
+            if [ -f "$GCLOUD_SDK_PATH/path.zsh.inc" ]; then . "$GCLOUD_SDK_PATH/path.zsh.inc"; fi
+            # The next line enables shell command completion for gcloud.
+            if [ -f "$GCLOUD_SDK_PATH/completion.zsh.inc" ]; then . "$GCLOUD_SDK_PATH/completion.zsh.inc"; fi
+            ;;
+
+        nvm)
+            # https://github.com/nvm-sh/nvm#uninstalling--removal
+            # To remove nvm manually, execute the following:
+            #   $ rm -rf "$NVM_DIR"
+            echo "Loading NVM integration"
+            export NVM_DIR="$HOME/.nvm"
+
+            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
+            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
+            ;;
+
+        aws)
+            echo "Load AWS profiles by running 'export AWS_PROFILE=<development/production/personal>'"
+            echo "All the profiles are sourced from '~/.aws/credentials'"
+            ;;
+
+        flutter)
+            echo "Loading Flutter integration"
+            [ -s "$HOME/flutter/bin/flutter" ] && export PATH="$PATH:$HOME/flutter/bin"
+            ;;
+
+        *)
+            echo "$0: error: unrecognized option $1"
+            echo "$0: $source_integrations_usage"
+            exit 1
+            ;;
+
+        esac
+        shift
+
+    done
+
+    # Make time only happen when triggered but in the end of the execution.
+    source_integrations_end=$(python3 -c 'from time import time; print(int(round(time() * 1000)))')
+    source_integrations_runtime=$((source_integrations_end - source_integrations_start))
+    echo "Runtime of sourcing integrations was $source_integrations_runtime ms."
 }
